# Use an official Python runtime as a base image
#FROM mysql:8.0.1
FROM mysql:5.5

ENV MYSQL_ROOT_PASSWORD passwordfortest

ENV MYSQL_DATABASE graphscale-unittest

ENV MYSQL_USER magnus

ENV MYSQL_PASSWORD magnus

# Set the working directory to /app
# WORKDIR /app
# 
# # Copy the current directory contents into the container at /app
# ADD . /app
# 
# # Install any needed packages specified in requirements.txt
# RUN pip install -r requirements.txt
# 
# # Make port 80 available to the world outside this container
# EXPOSE 80
# 
# # Define environment variable
# ENV NAME World
# 
# # Run app.py when the container launches
# CMD ["python", "app.py"]
